apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: calendar-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
        - name: calendar-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8888
          env:
            - name: RABBITMQ_URL
              value: {{ .Values.env.RABBITMQ_URL }}
            - name: POSTGRES_URL
              value: {{ .Values.env.POSTGRES_URL }}