FROM golang:1.23-alpine3.20 AS builder

# RUN apk update && apk add --no-cache git

WORKDIR /app
COPY . .

RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/calendar_scheduler ./cmd/scheduler

FROM alpine:latest

WORKDIR /app

COPY --from=builder /go/bin/calendar_scheduler /app/scheduler
COPY --from=builder /app/configs/config-deploy.yaml .

CMD ["/app/scheduler","--config","config-deploy.yaml","run"]